# use Ganache's forked mainnet mode as the default network
# NOTE: You don't *have* to do this, but it is often helpful for testing
networks:
    default: mainnet-fork

# automatically fetch contract sources from Etherscan
autofetch_sources: True

# require OpenZepplin Contracts
dependencies:
    - OpenZeppelin/openzeppelin-contracts-upgradeable@3.4.0
    - Badger-Finance/badger-vaults-1.5@exp-rewards.0
    - GalloDaSballo/badger-onchain-rewards@rfc.0.3

    - OpenZeppelin/openzeppelin-contracts@4.5.0 ## For BadgerRewards


# path remapping to support imports from GitHub/NPM
compiler:
    solc:
        remappings:
            - "@openzeppelin-contracts-upgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@3.4.0/contracts/"
            - "@badger-finance=Badger-Finance/badger-vaults-1.5@exp-rewards.0/contracts/"
            - "@badger-rewards=GalloDaSballo/badger-onchain-rewards@rfc.0.3/contracts/"

            - "@oz=OpenZeppelin/openzeppelin-contracts@4.5.0/contracts/" ## For BadgerRewards


reports:
    exclude_contracts:
        - SafeMath
